version: '3.8'

services:
  # Serviço da sua aplicação Clojure
  app:
    # Constrói a imagem usando o Dockerfile no diretório atual
    build: .
    container_name: clojure-api
    # Mapeia a porta do container para a sua máquina local
    ports:
      - "8080:8080"
    # Reinicia o container se ele parar
    restart: unless-stopped

  # Serviço do Grafana Agent para coletar as métricas
  grafana-agent:
    image: grafana/agent:latest
    container_name: grafana-agent
    ports:
      - "12345:12345" # Porta opcional para inspecionar o próprio agent
    volumes:
      # Mapeia o arquivo de configuração local para dentro do container do agent
      - ./agent.yaml:/etc/grafana-agent.yaml
    command:
      - "-config.file=/etc/grafana-agent.yaml"
    restart: unless-stopped
    # Garante que o agent só inicie depois que a 'app' estiver saudável
    depends_on:
      - app
