services:
  # Serviço para a sua API Clojure
  - type: web
    name: clojure-api
    env: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bigger-civet  # Nome do cluster CockroachDB
          property: connectionString

  # Serviço para o Grafana Agent
  - type: worker
    name: grafana-agent
    env: docker
    dockerImage: grafana/agent:latest
    dockerCommand: "-config.file=/etc/grafana-agent/agent.yaml"
    # REMOVIDO volumes pois não são suportados no Render
    envVars:
      - key: GRAFANA_REMOTE_WRITE_URL
        value: "sua_url_real_aqui"  # Substitua pelo valor real
      - key: GRAFANA_USERNAME
        value: "seu_username_real_aqui"  # Substitua pelo valor real
      - key: GRAFANA_API_KEY
        value: "sua_api_key_real_aqui"  # Substitua pelo valor real
